package github.oliveira.gb.librarycatalogapi.domain;

import github.oliveira.gb.librarycatalogapi.domain.author.Author;
import github.oliveira.gb.librarycatalogapi.domain.book.Book;
import github.oliveira.gb.librarycatalogapi.domain.book.BookStatus;
import github.oliveira.gb.librarycatalogapi.domain.category.Category;
import github.oliveira.gb.librarycatalogapi.domain.reader.Address;
import github.oliveira.gb.librarycatalogapi.domain.reader.Reader;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.hibernate.exception.ConstraintViolationException;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.springframework.transaction.annotation.Transactional;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

import java.time.Instant;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

/**
 * Integration tests for domain entities.
 * Validates JPA mapping, relationships, constraints, and auditing.
 * Following TDD approach as required by project standards.
 */
@DataJpaTest
@Testcontainers
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@Import(github.oliveira.gb.librarycatalogapi.infrastructure.config.JpaConfig.class)
@ActiveProfiles("test")
@Transactional
@DisplayName("Domain Entities Integration Tests")
class DomainEntitiesIntegrationTest {

    @Container
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>(DockerImageName.parse("postgres:16"))
            .withDatabaseName("catalog_test")
            .withUsername("test")
            .withPassword("test");

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        registry.add("spring.datasource.url", postgres::getJdbcUrl);
        registry.add("spring.datasource.username", postgres::getUsername);
        registry.add("spring.datasource.password", postgres::getPassword);
    }

    @PersistenceContext
    private EntityManager entityManager;

    private Category category;
    private Author author;

    @BeforeEach
    void setUp() {
        category = new Category();
        category.setName("Fiction");
        entityManager.persist(category);

        author = new Author();
        author.setName("John Doe");
        author.setEmail("john.doe@example.com");
        author.setBiography("A famous author");
        entityManager.persist(author);

        entityManager.flush();
    }

    @Nested
    @DisplayName("Category Entity Tests")
    class CategoryTests {

        @Test
        @DisplayName("Should persist category with auto-generated id and timestamps")
        void shouldPersistCategoryWithAutoGeneratedIdAndTimestamps() {
            Category newCategory = new Category();
            newCategory.setName("Science");

            entityManager.persist(newCategory);
            entityManager.flush();
            entityManager.clear();

            Category found = entityManager.find(Category.class, newCategory.getId());
            assertThat(found).isNotNull();
            assertThat(found.getId()).isNotNull();
            assertThat(found.getName()).isEqualTo("Science");
            assertThat(found.getActive()).isTrue();
            assertThat(found.getCreatedAt()).isNotNull();
            assertThat(found.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should enforce unique constraint on category name")
        void shouldEnforceUniqueConstraintOnCategoryName() {
            Category duplicate = new Category();
            duplicate.setName("Fiction");

            entityManager.persist(duplicate);

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(ConstraintViolationException.class);
        }
    }

    @Nested
    @DisplayName("Author Entity Tests")
    class AuthorTests {

        @Test
        @DisplayName("Should persist author with auto-generated id and timestamps")
        void shouldPersistAuthorWithAutoGeneratedIdAndTimestamps() {
            Author newAuthor = new Author();
            newAuthor.setName("Jane Smith");
            newAuthor.setEmail("jane.smith@example.com");
            newAuthor.setBiography("Another author");

            entityManager.persist(newAuthor);
            entityManager.flush();
            entityManager.clear();

            Author found = entityManager.find(Author.class, newAuthor.getId());
            assertThat(found).isNotNull();
            assertThat(found.getId()).isNotNull();
            assertThat(found.getName()).isEqualTo("Jane Smith");
            assertThat(found.getEmail()).isEqualTo("jane.smith@example.com");
            assertThat(found.getActive()).isTrue();
            assertThat(found.getCreatedAt()).isNotNull();
            assertThat(found.getUpdatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should enforce unique constraint on author email")
        void shouldEnforceUniqueConstraintOnAuthorEmail() {
            Author duplicate = new Author();
            duplicate.setName("Duplicate");
            duplicate.setEmail("john.doe@example.com");

            entityManager.persist(duplicate);

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(ConstraintViolationException.class);
        }
    }

    @Nested
    @DisplayName("Book Entity Tests")
    class BookTests {

        @Test
        @DisplayName("Should persist book with ManyToOne relationship to category")
        void shouldPersistBookWithManyToOneRelationshipToCategory() {
            Book book = new Book();
            book.setTitle("Test Book");
            book.setIsbn("978-3-16-148410-0");
            book.setCategory(category);

            entityManager.persist(book);
            entityManager.flush();
            entityManager.clear();

            Book found = entityManager.find(Book.class, book.getId());
            assertThat(found).isNotNull();
            assertThat(found.getTitle()).isEqualTo("Test Book");
            assertThat(found.getCategory()).isNotNull();
            assertThat(found.getCategory().getId()).isEqualTo(category.getId());
            assertThat(found.getStatus()).isEqualTo(BookStatus.DISPONIVEL);
            assertThat(found.getActive()).isTrue();
        }

        @Test
        @DisplayName("Should persist book with ManyToMany relationship to authors")
        void shouldPersistBookWithManyToManyRelationshipToAuthors() {
            Book book = new Book();
            book.setTitle("Collaborative Work");
            book.setIsbn("978-1-23-456789-0");
            book.setCategory(category);
            book.getAuthors().add(author);

            entityManager.persist(book);
            entityManager.flush();
            entityManager.clear();

            Book found = entityManager.find(Book.class, book.getId());
            assertThat(found.getAuthors()).hasSize(1);
            assertThat(found.getAuthors().iterator().next().getId()).isEqualTo(author.getId());
        }

        @Test
        @DisplayName("Should persist book status as string")
        void shouldPersistBookStatusAsString() {
            Book book = new Book();
            book.setTitle("Loaned Book");
            book.setIsbn("978-0-12-345678-9");
            book.setCategory(category);
            book.setStatus(BookStatus.EMPRESTADO);

            entityManager.persist(book);
            entityManager.flush();

            String statusInDb = (String) entityManager.createNativeQuery(
                    "SELECT status FROM books WHERE id = :id")
                    .setParameter("id", book.getId())
                    .getSingleResult();

            assertThat(statusInDb).isEqualTo("EMPRESTADO");
        }

        @Test
        @DisplayName("Should enforce unique constraint on book ISBN")
        void shouldEnforceUniqueConstraintOnBookIsbn() {
            Book book1 = new Book();
            book1.setTitle("First Book");
            book1.setIsbn("978-unique-isbn");
            book1.setCategory(category);
            entityManager.persist(book1);
            entityManager.flush();

            Book book2 = new Book();
            book2.setTitle("Second Book");
            book2.setIsbn("978-unique-isbn");
            book2.setCategory(category);

            entityManager.persist(book2);

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(ConstraintViolationException.class);
        }
    }

    @Nested
    @DisplayName("Reader Entity Tests")
    class ReaderTests {

        @Test
        @DisplayName("Should persist reader with embedded address")
        void shouldPersistReaderWithEmbeddedAddress() {
            Reader reader = new Reader();
            reader.setName("Test Reader");
            reader.setEmail("reader@example.com");
            reader.setCpf("123.456.789-00");

            Address address = new Address();
            address.setPostalCode("01310-100");
            address.setStreet("Avenida Paulista");
            address.setNumber("1000");
            address.setComplement("Apt 123");
            address.setNeighborhood("Bela Vista");
            address.setCity("São Paulo");
            address.setState("SP");
            reader.setAddress(address);

            entityManager.persist(reader);
            entityManager.flush();
            entityManager.clear();

            Reader found = entityManager.find(Reader.class, reader.getId());
            assertThat(found).isNotNull();
            assertThat(found.getName()).isEqualTo("Test Reader");
            assertThat(found.getAddress()).isNotNull();
            assertThat(found.getAddress().getStreet()).isEqualTo("Avenida Paulista");
            assertThat(found.getAddress().getCity()).isEqualTo("São Paulo");
            assertThat(found.getActive()).isTrue();
            assertThat(found.getCreatedAt()).isNotNull();
        }

        @Test
        @DisplayName("Should persist reader without address")
        void shouldPersistReaderWithoutAddress() {
            Reader reader = new Reader();
            reader.setName("Minimal Reader");
            reader.setEmail("minimal@example.com");
            reader.setCpf("987.654.321-00");

            entityManager.persist(reader);
            entityManager.flush();
            entityManager.clear();

            Reader found = entityManager.find(Reader.class, reader.getId());
            assertThat(found.getAddress()).isNull();
        }

        @Test
        @DisplayName("Should enforce unique constraint on reader email")
        void shouldEnforceUniqueConstraintOnReaderEmail() {
            Reader reader1 = new Reader();
            reader1.setName("First");
            reader1.setEmail("unique@example.com");
            reader1.setCpf("111.111.111-11");
            entityManager.persist(reader1);
            entityManager.flush();

            Reader reader2 = new Reader();
            reader2.setName("Second");
            reader2.setEmail("unique@example.com");
            reader2.setCpf("222.222.222-22");

            entityManager.persist(reader2);

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(ConstraintViolationException.class);
        }

        @Test
        @DisplayName("Should enforce unique constraint on reader CPF")
        void shouldEnforceUniqueConstraintOnReaderCpf() {
            Reader reader1 = new Reader();
            reader1.setName("First");
            reader1.setEmail("first@example.com");
            reader1.setCpf("333.333.333-33");
            entityManager.persist(reader1);
            entityManager.flush();

            Reader reader2 = new Reader();
            reader2.setName("Second");
            reader2.setEmail("second@example.com");
            reader2.setCpf("333.333.333-33");

            entityManager.persist(reader2);

            assertThatThrownBy(() -> entityManager.flush())
                    .isInstanceOf(ConstraintViolationException.class);
        }
    }

    @Nested
    @DisplayName("JPA Auditing Tests")
    class AuditingTests {

        @Test
        @DisplayName("Should automatically set createdAt and updatedAt on persist")
        void shouldAutomaticallySetCreatedAtAndUpdatedAtOnPersist() {
            Instant beforePersist = Instant.now();

            Category newCategory = new Category();
            newCategory.setName("Audited Category");

            entityManager.persist(newCategory);
            entityManager.flush();

            assertThat(newCategory.getCreatedAt()).isNotNull();
            assertThat(newCategory.getUpdatedAt()).isNotNull();
            assertThat(newCategory.getCreatedAt()).isAfterOrEqualTo(beforePersist);
            assertThat(newCategory.getUpdatedAt()).isEqualTo(newCategory.getCreatedAt());
        }
    }
}